:local = http://localhost:3335
:staging = http://fifa-elo-staging.herokuapp.com
:prod = http://fifa-elo.herokuapp.com

# check if the resources work
GET :local/css/tweaks.css

# check if the resources work
GET :local/js/compiled/app.js

# fetch all the leagues
GET :local/api/leagues

# fetch the league id page
GET :local/league/:league_id

# Fetch the css
GET :local/js/compiled/app.js?git_sha=1fda0a61-e581-407c-9f2e-9e51b7ce6491

# check why leagues list not coming up
GET :staging

# Check prod now
GET :prod

# Check that the github authentation works
GET :local/oauth2/github

# test the oauth2 callback to see what happens
GET :local/api/oauth2/github/callback?code=xxx&state=xxx

# check if a user is authenticated already
GET :local/authenticated