:local = http://localhost:9500
:staging = http://fifa-elo-staging.herokuapp.com
:prod = http://fifa-elo.herokuapp.com

# check if the resources work
GET :local/css/screen.css

# check if the resources work
GET :local/js/compiled/app.js

# fetch players
GET :local/api/players

# fetch all the leagues
GET :local/api/leagues

# fetch the league id page
GET :local/league/3564ef95-b84d-420f-8c85-31c6650458ad

# try again
GET :local/favicon.ico

# Fetch the css
GET :local/js/compiled/app.js?git_sha=1fda0a61-e581-407c-9f2e-9e51b7ce6491

# check why leagues list not coming up
GET :staging

# Check prod now
GET :prod

# Check that the github authentation works
GET :local/oauth2/github

# Fetch directly
GET http://localhost:3452/api/leagues

# fetch CSV data
GET :local/api/games-csv?league_id=640246a0-3153-4ae6-963c-75a5047a9e45

# fetch CSV data for the rankings
GET :local/api/rankings-csv?league_id=640246a0-3153-4ae6-963c-75a5047a9e45

# test the oauth2 callback to see what happens
GET :local/api/oauth2/github/callback?code=xxx&state=xxx