version: 2

references:
  base_config: &base_config
    working_directory: ~/elo
    docker:
      - image: circleci/clojure:lein-2.8.1

  base_docker: &base_docker
    working_directory: ~/elo
    docker:
      - image: circleci/clojure:lein-2.8.1
        environment:
          DATABASE_URL: postgres://elo@localhost/elo_test

      - image: postgres:10.4
        environment:
          POSTGRES_USER: elo
          POSTGRES_DB: elo_test

jobs:
  lint_clj:
    <<: *base_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein cljfmt check
      - run: lein eastwood

  test_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein migratus migrate
      - run: bin/kaocha --plugin kaocha.plugin/junit-xml --junit-xml-file test-results/kaocha/results.xml
      - store_test_results:
          path: test-results

      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein

          key: clj-deps-{{ checksum "project.clj" }}

  test_cljs:
    <<: *base_docker
    steps:
      - checkout
      - run: sudo apt install rhino
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein test-cljs || true

  coverage_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein migratus migrate
      - run: lein cloverage --codecov

      - store_test_results:
          path: target/test-results

      - store_artifacts:
          path: target/coverage

      - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - test_cljs
      - test_clj
      - coverage_clj
      - lint_clj
