version: 2

references:
  base_config: &base_config
    working_directory: ~/elo
    docker:
      - image: circleci/clojure:lein-2.8.1

  base_docker: &base_docker
    working_directory: ~/elo
    docker:
      - image: circleci/clojure:lein-2.8.1
        environment:
          DATABASE_URL: postgres://byf@localhost/byf_test
          TEST_DB_URL: postgres://byf@localhost/byf_test

      - image: postgres:10.4
        environment:
          POSTGRES_USER: byf
          POSTGRES_DB: byf_test

jobs:
  dependencies:
    <<: *base_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein

          key: clj-deps-{{ checksum "project.clj" }}

  lint_clj:
    <<: *base_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein cljfmt check
      - run: lein eastwood
  
  test_clj:
    <<: *base_docker

    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein migratus migrate
      - run: lein test2junit
      - store_test_results:
          path: target/test2junit

  coverage_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein migratus migrate
      - run: lein cloverage --codecov

      - store_test_results:
          path: target/test-results

      - store_artifacts:
          path: target/coverage

      - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - test_clj:
          requires:
            - dependencies

      - coverage_clj:
          requires:
            - dependencies

      - lint_clj:
          requires:
            - dependencies
