version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
        environment:
          DATABASE_URL: postgres://elo@localhost/elo_test

      - image: postgres:10.4
        environment:
          POSTGRES_USER: elo
          POSTGRES_DB: elo_test

    working_directory: ~/elo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - restore_cache:
          key: elo-{{ checksum "project.clj" }}

      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein
            - ~/.cljs/.aot_cache

          key: elo-{{ checksum "project.clj" }}

      - run: lein eastwood
      - run: lein migratus migrate
      - run: lein test2junit
      - store_test_results:
          path: target/test2junit

      # - run:
      #     name: run Clojurescript tests
      #     command: lein test-cljs
