version: 2

jobs:
  cljfmt:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          key: elo-{{ checksum "project.clj" }}
      - run:
          name: Check code formatting
          command: lein cljfmt check

  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
        environment:
          DATABASE_URL: postgres://elo@localhost/elo_test

      - image: postgres:10.4
        environment:
          POSTGRES_USER: elo
          POSTGRES_DB: elo_test

    working_directory: ~/elo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - restore_cache:
          key: elo-{{ checksum "project.clj" }}

      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: elo-{{ checksum "project.clj" }}

      - run: lein migratus migrate
      - run: lein test
      # - run: lein uberjar # to avoid discovering in deployment phase possible issues

workflows:
  version: 2
  jobs:
    - cljfmt
    - test:
        requires:
          - cljfmt
