version: 2

references:
  base_config: &base_config
    working_directory: ~/elo
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.391

  base_docker: &base_docker
    working_directory: ~/elo
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.391
        environment:
          DATABASE_URL: postgres://elo@localhost/elo_test

      - image: postgres:10.4
        environment:
          POSTGRES_USER: elo
          POSTGRES_DB: elo_test

jobs:
  cljfmt:
    <<: *base_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "deps.edn" }}

      - run: clojure -A:cljfmt
      - run: clojure -A:eastwood

  test_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "deps.edn" }}

      - run: bin/migrate
      - run: bin/kaocha --plugin kaocha.plugin/junit-xml --junit-xml-file test-results/kaocha/results.xml
      - store_test_results:
          path: test-results

      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein

          key: clj-deps-{{ checksum "deps.edn" }}

  coverage_clj:
    <<: *base_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "deps.edn" }}

      - run: bin/migrate
      - run: bin/kaocha --plugin cloverage --codecov

      - store_artifacts:
          path: target/coverage

      - run:
          name: Upload test coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - test_clj
      - coverage_clj
      - cljfmt
