version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
        environment:
          DATABASE_URL: postgres://elo@localhost/elo_test

      - image: postgres:10.4
        environment:
          POSTGRES_USER: elo
          POSTGRES_DB: elo_test

    working_directory: ~/elo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true

      - restore_cache:
          key: elo-{{ checksum "project.clj" }}

      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein
            - ~/.cljs/.aot_cache

          key: elo-{{ checksum "project.clj" }}

      - run: lein migratus migrate
      - run: lein test
      # move this to a frontend section
      - run:
          name: Install phantomjs
          command: |
            sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
            sudo chmod +x /usr/local/bin/phantomjs
            phantomjs -v

      # - run:
      #     name: run Clojurescript tests
      #     command: lein test-cljs
